ALTER TABLE users
    COMMENT = '用户账号与个人资料表',
    MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT '用户唯一标识',
    MODIFY COLUMN nickname VARCHAR(80) NOT NULL COMMENT '用户昵称，全局唯一',
    MODIFY COLUMN avatar_object_key VARCHAR(512) NULL COMMENT '头像在对象存储中的对象键',
    MODIFY COLUMN avatar_url VARCHAR(500) NULL COMMENT '头像访问地址（兼容历史数据）',
    MODIFY COLUMN bio VARCHAR(500) NOT NULL DEFAULT '' COMMENT '用户自我介绍',
    MODIFY COLUMN city VARCHAR(80) NOT NULL DEFAULT '' COMMENT '用户所在城市',
    MODIFY COLUMN status ENUM('ACTIVE','SUSPENDED','DELETED') NOT NULL DEFAULT 'ACTIVE' COMMENT '账号状态：ACTIVE正常，SUSPENDED停用，DELETED已删除',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '账号创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '账号资料最后更新时间',
    MODIFY COLUMN email VARCHAR(254) NULL COMMENT '登录邮箱，全局唯一',
    MODIFY COLUMN password_salt VARCHAR(64) NULL COMMENT '密码哈希使用的随机盐值',
    MODIFY COLUMN password_hash VARCHAR(128) NULL COMMENT '加盐后的密码哈希值';

ALTER TABLE posts
    COMMENT = '摄影作品与复刻作业主表',
    MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '作品唯一标识（UUID）',
    MODIFY COLUMN author_id VARCHAR(64) NOT NULL COMMENT '作者用户标识',
    MODIFY COLUMN kind ENUM('ORIGINAL','ASSIGNMENT') NOT NULL COMMENT '内容类型：ORIGINAL原创作品，ASSIGNMENT复刻作业',
    MODIFY COLUMN original_post_id CHAR(36) NULL COMMENT '复刻作业关联的原创作品标识',
    MODIFY COLUMN title VARCHAR(120) NOT NULL COMMENT '作品标题',
    MODIFY COLUMN description TEXT NOT NULL COMMENT '作品文案或说明',
    MODIFY COLUMN image_object_key VARCHAR(512) NULL COMMENT '原始图片在对象存储中的对象键',
    MODIFY COLUMN image_url VARCHAR(1000) NULL COMMENT '原始图片访问地址（兼容历史数据）',
    MODIFY COLUMN display_image_object_key VARCHAR(512) NULL COMMENT '详情展示图在对象存储中的对象键',
    MODIFY COLUMN display_image_url VARCHAR(1000) NULL COMMENT '详情展示图访问地址（兼容历史数据）',
    MODIFY COLUMN thumbnail_object_key VARCHAR(512) NULL COMMENT '缩略图在对象存储中的对象键',
    MODIFY COLUMN thumbnail_url VARCHAR(1000) NULL COMMENT '缩略图访问地址（兼容历史数据）',
    MODIFY COLUMN allow_remake BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否允许其他用户复刻',
    MODIFY COLUMN visibility ENUM('PUBLIC','PRIVATE') NOT NULL DEFAULT 'PUBLIC' COMMENT '可见范围：PUBLIC公开，PRIVATE私密',
    MODIFY COLUMN review_status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'APPROVED' COMMENT '审核状态：PENDING待审核，APPROVED通过，REJECTED拒绝',
    MODIFY COLUMN shooting_notes TEXT NOT NULL COMMENT '拍摄思路与现场说明',
    MODIFY COLUMN editing_notes TEXT NOT NULL COMMENT '后期处理说明',
    MODIFY COLUMN reused_notes TEXT NOT NULL COMMENT '复刻时沿用的内容',
    MODIFY COLUMN adjusted_notes TEXT NOT NULL COMMENT '复刻时调整的内容',
    MODIFY COLUMN assignment_notes TEXT NOT NULL COMMENT '复刻作业心得',
    MODIFY COLUMN is_recommended BOOLEAN NOT NULL DEFAULT FALSE COMMENT '复刻作业是否被原作者推荐',
    MODIFY COLUMN like_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数量缓存',
    MODIFY COLUMN comment_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论数量缓存',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '作品发布时间',
    MODIFY COLUMN updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '作品最后更新时间',
    MODIFY COLUMN deleted_at TIMESTAMP(3) NULL COMMENT '软删除时间，空值表示未删除';

ALTER TABLE capture_metadata
    COMMENT = '作品拍摄参数与EXIF信息表',
    MODIFY COLUMN post_id CHAR(36) NOT NULL COMMENT '所属作品标识',
    MODIFY COLUMN camera_make VARCHAR(120) NOT NULL DEFAULT '' COMMENT '相机制造商',
    MODIFY COLUMN camera_model VARCHAR(160) NOT NULL DEFAULT '' COMMENT '相机型号',
    MODIFY COLUMN camera_display VARCHAR(240) NOT NULL DEFAULT '' COMMENT '用于页面展示的相机名称',
    MODIFY COLUMN lens_model VARCHAR(240) NOT NULL DEFAULT '' COMMENT '镜头型号',
    MODIFY COLUMN focal_length_mm DECIMAL(8,2) NULL COMMENT '焦距，单位毫米',
    MODIFY COLUMN aperture DECIMAL(6,2) NULL COMMENT '光圈F值',
    MODIFY COLUMN shutter_seconds DECIMAL(14,8) NULL COMMENT '快门时间，单位秒',
    MODIFY COLUMN iso INT UNSIGNED NULL COMMENT 'ISO感光度',
    MODIFY COLUMN exposure_compensation DECIMAL(6,2) NULL COMMENT '曝光补偿值（EV）',
    MODIFY COLUMN captured_at DATETIME NULL COMMENT '照片实际拍摄时间',
    MODIFY COLUMN source ENUM('EXIF','USER_CONFIRMED','MANUAL') NOT NULL DEFAULT 'MANUAL' COMMENT '参数来源：EXIF自动读取，USER_CONFIRMED用户确认，MANUAL手动填写',
    MODIFY COLUMN raw_exif JSON NULL COMMENT '原始EXIF数据';

ALTER TABLE post_locations
    COMMENT = '作品拍摄地点信息表',
    MODIFY COLUMN post_id CHAR(36) NOT NULL COMMENT '所属作品标识',
    MODIFY COLUMN place_name VARCHAR(200) NOT NULL DEFAULT '' COMMENT '拍摄地点名称',
    MODIFY COLUMN city VARCHAR(80) NOT NULL DEFAULT '' COMMENT '拍摄地点所在城市',
    MODIFY COLUMN district VARCHAR(100) NOT NULL DEFAULT '' COMMENT '拍摄地点所在区县',
    MODIFY COLUMN detailed_address VARCHAR(500) NOT NULL DEFAULT '' COMMENT '可编辑的详细地址',
    MODIFY COLUMN privacy_level ENUM('EXACT','APPROXIMATE','PRIVATE') NOT NULL DEFAULT 'PRIVATE' COMMENT '地点公开级别：EXACT精确，APPROXIMATE模糊，PRIVATE不公开',
    MODIFY COLUMN latitude DECIMAL(10,7) NULL COMMENT '原始纬度',
    MODIFY COLUMN longitude DECIMAL(10,7) NULL COMMENT '原始经度',
    MODIFY COLUMN public_latitude DECIMAL(10,7) NULL COMMENT '对外展示的纬度',
    MODIFY COLUMN public_longitude DECIMAL(10,7) NULL COMMENT '对外展示的经度',
    MODIFY COLUMN shooting_advice VARCHAR(300) NOT NULL DEFAULT '' COMMENT '该地点的拍摄建议',
    MODIFY COLUMN safety_status ENUM('NORMAL','CAUTION','RESTRICTED') NOT NULL DEFAULT 'NORMAL' COMMENT '地点安全状态：NORMAL正常，CAUTION谨慎，RESTRICTED受限';

ALTER TABLE post_likes
    COMMENT = '用户作品点赞关系表',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '点赞用户标识',
    MODIFY COLUMN post_id CHAR(36) NOT NULL COMMENT '被点赞作品标识',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '点赞时间';

ALTER TABLE favorites
    COMMENT = '用户作品收藏关系表（历史功能保留）',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '收藏用户标识',
    MODIFY COLUMN post_id CHAR(36) NOT NULL COMMENT '被收藏作品标识',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '收藏时间';

ALTER TABLE comments
    COMMENT = '作品评论表',
    MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '评论唯一标识（UUID）',
    MODIFY COLUMN post_id CHAR(36) NOT NULL COMMENT '所属作品标识',
    MODIFY COLUMN author_id VARCHAR(64) NOT NULL COMMENT '评论作者用户标识',
    MODIFY COLUMN parent_id CHAR(36) NULL COMMENT '回复的上级评论标识，空值表示一级评论',
    MODIFY COLUMN content VARCHAR(1000) NOT NULL COMMENT '评论内容',
    MODIFY COLUMN status ENUM('VISIBLE','HIDDEN','DELETED') NOT NULL DEFAULT 'VISIBLE' COMMENT '评论状态：VISIBLE可见，HIDDEN隐藏，DELETED已删除',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '评论创建时间',
    MODIFY COLUMN updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '评论最后更新时间';

ALTER TABLE follows
    COMMENT = '用户关注关系表',
    MODIFY COLUMN follower_id VARCHAR(64) NOT NULL COMMENT '发起关注的用户标识',
    MODIFY COLUMN following_id VARCHAR(64) NOT NULL COMMENT '被关注的用户标识',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '关注时间';

ALTER TABLE remake_plans
    COMMENT = '用户拍摄计划表',
    MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '拍摄计划唯一标识（UUID）',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '计划所属用户标识',
    MODIFY COLUMN original_post_id CHAR(36) NOT NULL COMMENT '计划复刻的原创作品标识',
    MODIFY COLUMN status ENUM('PLANNED','COMPLETED') NOT NULL DEFAULT 'PLANNED' COMMENT '计划状态：PLANNED待拍摄，COMPLETED已完成',
    MODIFY COLUMN completed_assignment_id CHAR(36) NULL COMMENT '完成计划后提交的复刻作业标识',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '加入拍摄计划时间',
    MODIFY COLUMN completed_at TIMESTAMP(3) NULL COMMENT '完成拍摄计划时间';

ALTER TABLE content_reports
    COMMENT = '用户内容举报记录表',
    MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '举报记录唯一标识（UUID）',
    MODIFY COLUMN reporter_id VARCHAR(64) NOT NULL COMMENT '举报人用户标识',
    MODIFY COLUMN target_type ENUM('POST','COMMENT','USER','LOCATION') NOT NULL COMMENT '举报对象类型：POST作品，COMMENT评论，USER用户，LOCATION地点',
    MODIFY COLUMN target_id VARCHAR(64) NOT NULL COMMENT '被举报对象标识',
    MODIFY COLUMN reason VARCHAR(80) NOT NULL COMMENT '举报原因',
    MODIFY COLUMN description VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '举报补充说明',
    MODIFY COLUMN status ENUM('OPEN','RESOLVED','REJECTED') NOT NULL DEFAULT 'OPEN' COMMENT '处理状态：OPEN待处理，RESOLVED已处理，REJECTED已驳回',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '举报创建时间',
    MODIFY COLUMN handled_at TIMESTAMP(3) NULL COMMENT '举报处理完成时间';

ALTER TABLE user_sessions
    COMMENT = '用户登录会话表',
    MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '会话唯一标识（UUID）',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '会话所属用户标识',
    MODIFY COLUMN token_hash CHAR(64) NOT NULL COMMENT '登录令牌的SHA-256哈希值',
    MODIFY COLUMN expires_at TIMESTAMP(3) NOT NULL COMMENT '会话过期时间',
    MODIFY COLUMN created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '会话创建时间';
